intro.windowTitle=Интро

intro.crawl.1=ЭПИЗОД I
intro.crawl.2=АЛКОСМЕН: НОЧНОЙ ЗАХОД
intro.crawl.3=
intro.crawl.4=Ночной город не спит.
intro.crawl.5=Фонари трещат, район шумит.
intro.crawl.6=Менты уже на патруле.
intro.crawl.7=
intro.crawl.8=Первый уровень
intro.crawl.9=временно отключен.

intro.scroll.delay.ms=20
intro.scroll.step=2

intro.sub.1.timeMs=0
intro.sub.1.text=ЭПИЗОД I. Алкосмен выходит на ночной заход.
intro.sub.2.timeMs=3200
intro.sub.2.text=Ночной город не спит.
intro.sub.3.timeMs=6200
intro.sub.3.text=Фонари трещат, район шумит.
intro.sub.4.timeMs=9200
intro.sub.4.text=Менты уже на патруле.
intro.sub.5.timeMs=12400
intro.sub.5.text=Первый уровень временно отключен.
